# This is what want to change the wrong file

# - id: uri:http://www.aaai.org/ocs/index.php/AAAI/AAAI11/paper/view/3570
#   type: paper
#   # description: 
#   date: 2020-12-4
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
#   tags:
#     - open science
#     - collaboration
#   repo: greenelab/meta-review
#   link: https://ojs.aaai.org/index.php/AAAI/article/view/8080