# This is what want to change the wrong file

- id: byG9xLMAAAAJ:RGFaLdJalmkC
  type: paper
  # description: 
  date: 2023-09-6
  image: images/research/happy.png
  buttons:
    # - type: manubot
    #   link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/Jthy-af/HaPPy
    - type: website
      link: 
  tags:
    - drug design
    - Ai for Science
  # repo: greenelab/meta-review
  link: https://doi.org/10.1609/aaai.v37i13.27052